# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18e01566e83d3f0a9e2380d104f35aaadd1d8d2be78b048294a8bf21b0cd6d3f82f81a5fef3398457d98ff7981e7faf107e0018191716e960bd915959f0e74a5

test:
  secret_key_base: 4e0b044db8eade0b438a55ed3428c88f41779b29ea1ba178142085b5033418d528909dc39f00127e4c1837bb3f72334fccca9cf688336ef40959040b7c4fa0ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
